# Generated by Django 6.0.4 on 2026-04-21 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True)),
                ('estado', models.CharField(choices=[('ESPERANDO', 'Esperando'), ('JUGANDO', 'Jugando'), ('FINALIZADA', 'Finalizada')], default='ESPERANDO', max_length=20)),
                ('palabra_secreta', models.CharField(blank=True, max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('max_jugadores', models.IntegerField(default=6)),
                ('num_impostores', models.IntegerField(default=1)),
                ('es_publica', models.BooleanField(default=True)),
                ('ronda_actual', models.IntegerField(default=0)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_totales', models.IntegerField(default=0)),
                ('partidas_jugadas', models.IntegerField(default=0)),
                ('victorias', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartidaJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('IMPOSTOR', 'Impostor')], max_length=10)),
                ('palabra_escrita', models.CharField(blank=True, max_length=10)),
                ('eliminado', models.BooleanField(default=False)),
                ('puntos_obtenidos', models.IntegerField(default=0)),
                ('unido_en', models.DateTimeField(auto_now_add=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='game.partida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_jugadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('partida', 'usuario')},
            },
        ),
    ]
